dist: trusty
branches:
  only:
  - travis-build
language: node_js
jdk: oraclejdk8
node_js:
  - "6"
script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && cd client && npm install && npm test

